### ISSUE TITLE
flow logs not available

### ISSUE THREAD

**Issue by exeding** [aws-samples/aws-network-firewall-terraform#2]
hey there,

i was just testing the code and it seems that the output of flow-logs to s3 is not working.
i can successfully deploy the terraformcode and everything works as expected, but within the s3 bucket now flowlogs are appearing.

Is there maybe a permission missing that must be deployed via terraform as stated in the docs?
https://docs.aws.amazon.com/network-firewall/latest/developerguide/logging-s3.html

kind regards,
Thomas

**Comment by nicoaws** [comment]
hi Thomas, what does your S3 bucket policy looks like (please omit confidential information such Account IDs or KMS key IDs)?

**Comment by nicoaws** [comment]
Thanks for reporting Thomas, 
the wrong S3 bucket encryption was specified. This is now corrected and tested.
Closed in https://github.com/aws-samples/aws-network-firewall-terraform/commit/c2aa7c17686b4e85952988a3ceb94d96d270976a

**Comment by exeding** [comment]
Thanks for that fast response and solution :)
